apiVersion: v2
name: boilerplate
description: Boilerplate templates
type: library
version: 0.15.1
icon: https://raw.githubusercontent.com/self-hosters-by-night/helm-charts/refs/heads/main/assets/boilerplate.png
