version: 2
updates:
- package-ecosystem: "github-actions"
  directory: ".github/workflows"
  schedule:
    interval: "weekly"
- package-ecosystem: "helm"
  directory: "charts"
  schedule:
    interval: "weekly"
