apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ randAlphaNum 48 | b64enc }}
