{{- if .Values.meilisearch.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meilisearch
spec:
  secretStoreRef:
    kind: SecretStore
    name: openbao-{{ .Chart.Name }}
  target:
    name: meilisearch
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: shbn/karakeep/meilisearch
{{- end }}
