{{- if not (lookup "v1" "Secret" .Release.Namespace "meilisearch") }}
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  MEILI_MASTER_KEY: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}
