{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  {{- with .Values.cronjob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- with .Values.cronjob.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  {{- with .Values.cronjob.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.suspend }}
  suspend: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        {{- include "boilerplate.labels.standard" . | nindent 8 }}
      {{- with .Values.cronjob.jobAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.cronjob.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      {{- with .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "boilerplate.labels.standard" . | nindent 12 }}
          {{- with .Values.cronjob.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- include "boilerplate.images.pullSecrets" (dict "image" .Values.cronjob.image "global" .Values.global) | nindent 10 }}
          serviceAccountName: {{ include "boilerplate.names.serviceAccountName" . }}
          {{- with .Values.cronjob.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy | default "OnFailure" }}
          containers:
            - name: {{ .Chart.Name }}
              image: {{ include "boilerplate.images.image" (dict "image" .Values.cronjob.image "global" .Values.global "chart" .Chart) }}
              imagePullPolicy: {{ include "boilerplate.images.pullPolicy" (dict "image" .Values.cronjob.image "global" .Values.global) }}
              {{- with .Values.cronjob.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cronjob.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cronjob.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cronjob.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.cronjob.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- include "boilerplate.storage.extraVolumeMounts" . | nindent 16 }}
              {{- with .Values.cronjob.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            {{- include "boilerplate.storage.extraVolumes" . | nindent 12 }}
          {{- with .Values.cronjob.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronjob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronjob.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronjob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
