{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- range .Values.httproute.parentRefs }}
  - name: {{ .name }}
    {{- with .namespace }}
    namespace: {{ . }}
    {{- end }}
    {{- with .sectionName }}
    sectionName: {{ . }}
    {{- end }}
    {{- with .port }}
    port: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.httproute.rules }}
  - matches:
    {{- range .matches }}
    - path:
        {{- with .path.type }}
        type: {{ . }}
        {{- end }}
        {{- with .path.value }}
        value: {{ . }}
        {{- end }}
      {{- with .method }}
      method: {{ . }}
      {{- end }}
      {{- with .headers }}
      headers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .queryParams }}
      queryParams:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name | default (include "boilerplate.names.fullname" $) }}
      port: {{ .port | default $.Values.service.port }}
      {{- with .weight }}
      weight: {{ . }}
      {{- end }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
    {{- end }}
    {{- with .filters }}
    filters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
