{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- range .Values.rbac.rules }}
- apiGroups:
  {{- range .apiGroups }}
  - {{ . | quote }}
  {{- end }}
  resources:
  {{- range .resources }}
  - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .verbs }}
  - {{ . | quote }}
  {{- end }}
  {{- with .resourceNames }}
  resourceNames:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
