{{- if .Values.tcproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  {{- with .Values.tcproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- range .Values.tcproute.parentRefs }}
  - name: {{ .name }}
    {{- with .namespace }}
    namespace: {{ . }}
    {{- end }}
    {{- with .sectionName }}
    sectionName: {{ . }}
    {{- end }}
    {{- with .port }}
    port: {{ . }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.tcproute.rules }}
  - backendRefs:
    {{- range .backendRefs }}
    - name: {{ .name | default (include "boilerplate.names.fullname" $) }}
      port: {{ .port | default $.Values.service.port }}
      {{- with .weight }}
      weight: {{ . }}
      {{- end }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
