{{- if empty .Values.secrets.existingSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "boilerplate.names.fullname" . }}-secret
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: openbao-{{ .Chart.Name }}
  target:
    name: {{ include "boilerplate.names.fullname" . }}-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: lldap
{{- end }}
