{{- if and .Values.backup.persistence.enabled (eq .Values.backup.persistence.existingClaim "") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "boilerplate.names.name" . }}-backups
spec:
  storageClassName: {{ .Values.backup.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
{{- end }}
