apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-postgres.name" . }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "simple-postgres.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "simple-postgres.selectorLabels" . | nindent 4 }}
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: simple-postgres
      port: {{ .Values.postgres.service.port }}
      protocol: TCP
      targetPort: postgres
