{{- if and .Values.networkPolicies.enabled (eq .Values.networkPolicies.flavor "kubernetes") -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "boilerplate.labels.selectorLabels" . | nindent 8 }}
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
    - to: []
      ports:
        - port: 443
          protocol: TCP
    # Chrome service
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: chrome
      ports:
        - port: 9222
          protocol: TCP
    # Meilisearch service
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: meilisearch
      ports:
        - port: 7700
          protocol: TCP
  ingress:
    - from: []
      ports:
        - port: 8080
          protocol: TCP
{{- end }}
