{{- if .Values.cronJob.spinachConfiguration -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boilerplate.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  spinach.yml: |
    {{- .Values.cronJob.spinachConfiguration | toYaml | nindent 4 }}
{{- end -}}
