apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "boilerplate.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  failedJobsHistoryLimit: {{ .Values.cronJob.history.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.history.successfulJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "boilerplate.labels.standard" . | nindent 8 }}
      namespace: {{ .Release.Namespace }}
    spec:
      template:
        metadata:
          labels:
            {{- include "boilerplate.labels.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "boilerplate.names.serviceAccountName" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              image: {{ include "boilerplate.images.image" (dict "image" .Values.image "global" .Values.global "chart" .Chart) }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- if .Values.cronJob.configuration }}
                - "-f /home/spinach.yml"
                {{- end }}
                {{- if .Values.cronJob.clusterName }}
                - --cluster-name={{ .Values.cronJob.clusterName }}
                {{- end }}
                - --force-exit-zero=true
                - --out={{ .Values.cronJob.outputFormat }}
                {{- if and (eq .Values.cronJob.outputFormat "prometheus") (.Values.cronJob.prometheus.pushgatewayAddress) }}
                - --push-gtwy-url={{ .Values.cronJob.prometheus.pushgatewayAddress }}
                {{- if .Values.cronJob.prometheus.basicAuth.enabled }}
                - --push-gtwy-user={{ .Values.cronJob.prometheus.basicAuth.user }}
                - --push-gtwy-password=$PUSHGATEWAY_BASIC_AUTH_PASSWORD
                {{- end }}
                {{- end }}
                {{- if .Values.cronJob.s3.bucket }}
                - --s3-bucket={{ .Values.cronJob.s3.bucket }}
                {{- end }}
                {{- if .Values.cronJob.s3.region }}
                - --s3-region={{ .Values.cronJob.s3.region }}
                {{- end }}
                {{- if .Values.cronJob.s3.endpoint }}
                - --s3-endpoint={{ .Values.cronJob.s3.endpoint }}
                {{- end }}
              {{- if and (eq .Values.cronJob.outputFormat "prometheus") (.Values.cronJob.prometheus.pushgatewayAddress) (.Values.cronJob.prometheus.basicAuth.enabled) }}
              env:
                - name: PUSHGATEWAY_BASIC_AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "boilerplate.names.fullname" . }}-prometheus
                      key: pushgateway-password
              {{- end }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if .Values.cronJob.configuration }}
              volumeMounts:
                - name: configuration
                  mountPath: /home
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.cronJob.configuration }}
          volumes:
            - name: configuration
              configMap:
                name: {{ include "boilerplate.names.fullname" . }}
          {{- end }}
