# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: ghcr.io
  repository: lldap/lldap
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # Possible tags:
  #   latest-debian
  #   latest-alpine
  #   latest-debian-rootless
  #   latest-alpine-rootless
  #   yyyy-mm-dd-latest-debian
  #   yyyy-mm-dd-latest-alpine
  #   yyyy-mm-dd-latest-debian-rootless
  #   yyyy-mm-dd-latest-alpine-rootless
  # Check out https://github.com/lldap/lldap/pkgs/container/lldap for a complete list of available tags

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Service configuration
service:
  # Service type
  type: ClusterIP

  # Annotations for the service (useful for cloud provider load balancers)
  annotations: {}
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"

  # LoadBalancer specific configuration
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
    # - 10.0.0.0/8
    # - 192.168.0.0/16

  # LDAP service configuration
  ldap:
    port: 3890
    # nodePort: 30389  # Only used if service.type is NodePort or LoadBalancer

  # LDAPS service configuration
  ldaps:
    port: 6360
    # nodePort: 30636  # Only used if service.type is NodePort or LoadBalancer

  # HTTP web interface configuration
  webui:
    port: 17170
    # nodePort: 30171  # Only used if service.type is NodePort or LoadBalancer

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
