apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "boilerplate.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "boilerplate.labels.standard" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "boilerplate.images.image"
            ( dict
              "root" .
              "image" .Values.image
            ) | nindent 10
          }}
          {{- include "boilerplate.images.pullPolicy"
            ( dict
              "globalPullPolicy" .Values.global.imagePullPolicy
              "localPullPolicy" .Values.image.pullPolicy
            ) | nindent 10
          }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.configMapRefs .Values.extraConfigMapRefs .Values.secretRefs .Values.extraSecretRefs }}
          envFrom:
            {{- range .Values.configMapRefs }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
            {{- range .Values.extraConfigMapRefs }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
            {{- range .Values.secretRefs }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
            {{- range .Values.extraSecretRefs }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3214
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: {{ .Values.persistence.config.name | default "config" }}
              mountPath: {{ .Values.persistence.config.mountPath | default "/config" }}
            {{- end }}
            {{- if .Values.persistence.libraries.enabled }}
            - name: {{ .Values.persistence.libraries.name | default "libraries" }}
              mountPath: {{ .Values.persistence.libraries.mountPath | default "/libraries" }}
            {{- end }}
            {{- include "boilerplate.storage.extraVolumeMounts" . | nindent 12 }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: {{ .Values.persistence.config.name | default "config" }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim | default (printf "%s-config" (include "boilerplate.names.fullname" .)) }}
        {{- end }}
        {{- if .Values.persistence.libraries.enabled }}
        - name: {{ .Values.persistence.libraries.name | default "libraries" }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.libraries.existingClaim | default (printf "%s-libraries" (include "boilerplate.names.fullname" .)) }}
        {{- end }}
        {{- include "boilerplate.storage.extraVolumes" . | nindent 8 }}
