apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boilerplate.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "boilerplate.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "boilerplate.labels.standard" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "boilerplate.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.secret_key_base.secret .Values.secret_key_base.secretKeyRef }}
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secret_key_base.secret }}
                    name: {{ include "boilerplate.fullname" . }}
                    key: "SECRET_KEY_BASE"
                  {{- else }}
                    name: {{ .Values.secret_key_base.secretKeyRef.name }}
                    key: {{ .Values.secret_key_base.secretKeyRef.key }}
                  {{- end }}
          {{- end }}
          {{- with .Values.secret_key_base.secretName }}
          envFrom:
            - secretRef:
              name: {{ .name }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: manyfold-config
              mountPath: /config
            - name: manyfold-libraries
              mountPath: /libraries
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3214
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: manyfold-config
          persistentVolumeClaim:
            claimName: manyfold-config
        - name: manyfold-libraries
          persistentVolumeClaim:
            claimName: manyfold-libraries
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
