apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: openbao-{{ .Chart.Name }}
  target:
    name: {{ include "boilerplate.names.fullname" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: shbn/manyfold
