{{- if hasKey .Values.env "SECRET_KEY_BASE" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
data:
  SECRET_KEY_BASE: {{ .Values.env.SECRET_KEY_BASE | b64enc | quote }}
{{- end }}
