apiVersion: v2
name: manyfold
description: "Manyfold is a self-hosted digital asset manager for 3d print files."
type: application
version: 0.7.0
appVersion: "0.147.2"
icon: https://raw.githubusercontent.com/manyfold3d/manyfold/main/app/frontend/images/roundel.svg
annotations:
  artifacthub.io/category: storage
maintainers:
  - name: facorazza
    email: git@facorazza.com
dependencies:
  - name: boilerplate
    version: 0.16.0
    repository: "https://self-hosters-by-night.github.io/helm-charts"
  - name: postgres
    version: 0.14.3
    repository: "https://self-hosters-by-night.github.io/helm-charts"
    condition: postgres.enabled
  - name: valkey
    version: 0.1.0
    repository: "https://self-hosters-by-night.github.io/helm-charts"
    condition: valkey.enabled
