
# Global values for boilerplate compatibility
global:
  imageRegistry: ""
  imagePullPolicy: ""

image:
  registry: ghcr.io
  repository: manyfold3d/manyfold-solo
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent

nodeSelector: {}
tolerations: []
affinity: {}

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @param env Environment variables to add to the container
env:
  vars:
    SECRET_KEY_BASE: "CHANGE-ME-OR-USE-SECRET"
  fromConfigMap: {}
  # ENV_VAR_NAME:
  #     from: configmap-name
  #     key: configmap-key
  #     optional: false
  fromSecret: {}
  # SECRET_NAME:
  #     from: secret-name
  #     key: secret-key
  #     optional: false

envFrom:
  configMaps: []
  # - name: s3-config

  secrets: []
  #  - name: s3-config

# Persistence configuration
persistence:
  config:
    enabled: true
    name: "config"
    mountPath: "/config"
    existingClaim: ""
  libraries:
    enabled: true
    name: "libraries"
    mountPath: "/libraries"
    existingClaim: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: manyfold.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: manyfold-tls
  #    hosts:
  #      - manyfold.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30

# Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
