apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-{{ .Chart.Name }}
spec:
  provider:
    vault:
      server: http://openbao.openbao:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ .Chart.Name }}
          serviceAccountRef:
            name: {{ include "boilerplate.names.serviceAccountName" . }}
