apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
data:
  mosquitto.conf: | {{ .Values.config | nindent 4 }}
