apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "boilerplate.labels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "boilerplate.labels.podLabels" . | nindent 8 }}
    spec:
      {{- include "boilerplate.images.pullSecrets"
        ( dict
          "globalImagePullSecrets" .Values.global.imagePullSecrets
          "localImagePullSecrets" .Values.image.pullSecrets
        ) | nindent 6
      }}
      serviceAccountName: {{ include "boilerplate.names.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- include "boilerplate.images.image"
            ( dict
              "root" .
              "image" .Values.image
            ) | nindent 10
          }}
          {{- include "boilerplate.images.pullPolicy"
            ( dict
              "globalPullPolicy" .Values.global.imagePullPolicy
              "localPullPolicy" .Values.image.pullPolicy
            ) | nindent 10
          }}
          {{- include "boilerplate.environment.env" ( dict "env" .Values.env "global" .Values.global ) | indent 10 }}
          {{- include "boilerplate.environment.envFrom" ( dict "envFrom" .Values.envFrom "global" .Values.global ) | indent 10 }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            {{- include "boilerplate.storage.extraVolumeMounts" . | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "boilerplate.names.fullname" . }}
            defaultMode: 0700
            items:
              - key: mosquitto.conf
                path: mosquitto.conf
        {{- include "boilerplate.storage.extraVolumes" . | indent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
