apiVersion: v1
kind: Service
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
  {{- include "boilerplate.labels.commonAnnotations" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 9001
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "boilerplate.labels.selectorLabels" . | nindent 4 }}
