{{- if and .Values.networkPolicy.enabled (or (not .Values.networkPolicy.flavor) (eq .Values.networkPolicy.flavor "kubernetes")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "boilerplate.names.fullname" . }}
  labels:
    {{- include "boilerplate.labels.standard" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "boilerplate.labels.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      - podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
    # Allow CoreDNS (alternative DNS setup)
    - to:
      - namespaceSelector:
          matchLabels:
            name: kube-system
      - podSelector:
          matchLabels:
            k8s-app: coredns
      ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
    # Allow external HTTP/HTTPS traffic
    - to: []
      ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
  ingress:
    # Allow ingress from ingress controllers
    - from: []
      ports:
      - protocol: TCP
        port: {{ .Values.containerPort | default 8080 }}
{{- end }}
