apiVersion: v2
name: chrome
description: A Helm chart for Chrome
type: application
version: 0.1.0
appVersion: "124"
maintainers:
  - name: facorazza
    email: git@facorazza.com
dependencies:
  - name: boilerplate
    version: "0.1.0"
    repository: "https://github.com/self-hosters-by-night/helm-charts"
